spring.application.name=inventariado

# ==============================================
# BASE DE DATOS (MySQL)
# ==============================================
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================================
# CORREO (Spring Mail / Gmail SMTP)
# ==============================================
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true

# ==============================================
# SEGURIDAD JWT
# ==============================================
jwt.secret=

# ==============================================
# REDIS (Caché & Blacklist)
# ==============================================
spring.data.redis.host=
spring.data.redis.port=

# ==============================================
# PUERTO DEL SERVIDOR
# ==============================================
server.port=
